# netlify.toml

# إعدادات البناء الأساسية
[build]
  command = "pnpm run build"
  publish = "dist"

# --- قواعد إعادة التوجيه (البروكسي) ---

# القاعدة الأولى: خاصة بالقرآن والقرآءات
[[redirects]]
  from = "/quran-api/*"  # أي طلب يبدأ بـ /quran-api/...
  to = "https://api.quranpedia.net/v1/:splat" # ...حوله إلى API القرآءات
  status = 200

# القاعدة الثانية: خاصة بالباك إند القديم (للأحاديث)
[[redirects]]
  from = "/api/*"
  to = "https://radwan2633.pythonanywhere.com/:splat"
  status = 200
