# netlify.toml

# ุฅุนุฏุงุฏุงุช ุงูุจูุงุก ุงูุฃุณุงุณูุฉ
[build]
  command = "pnpm run build"
  publish = "dist"

# --- ููุงุนุฏ ุฅุนุงุฏุฉ ุงูุชูุฌูู (ุงูุจุฑููุณู) ---
# ุงููุงุนุฏุฉ ุงูุฃูุซุฑ ุชุญุฏูุฏูุง ุชุฃุชู ุฃููุงู

# ุงููุงุนุฏุฉ ุงูุฃููู: ุฎุงุตุฉ ุจุงููุฑุขู ูุงููุฑุขุกุงุช
[[redirects]]
  from = "/quran-api/*"
  to = "https://api.quranpedia.net/v1/:splat"
  status = 200
  force = true # ๐ ุฅุถุงูุฉ ุฌุฏูุฏุฉ: ูุฅุฌุจุงุฑ Netlify ุนูู ุงุณุชุฎุฏุงู ูุฐู ุงููุงุนุฏุฉ

# ุงููุงุนุฏุฉ ุงูุซุงููุฉ: ุฎุงุตุฉ ุจุงูุจุงู ุฅูุฏ ุงููุฏูู (ููุฃุญุงุฏูุซ)
[[redirects]]
  from = "/hadith-api/*" # ๐ ุชุบููุฑ ุงููุณุงุฑ ููููู ุฃูุซุฑ ูุถูุญูุง
  to = "https://radwan2633.pythonanywhere.com/:splat"
  status = 200
  force = true # ๐ ุฅุถุงูุฉ ุฌุฏูุฏุฉ: ูุฅุฌุจุงุฑ Netlify ุนูู ุงุณุชุฎุฏุงู ูุฐู ุงููุงุนุฏุฉ
