# netlify.toml

# إعدادات البناء الأساسية
[build]
  command = "pnpm run build"
  publish = "dist"

# القاعدة الوحيدة التي نحتاجها هي للباك إند الخاص بالأحاديث
[[redirects]]
  from = "/api/*"
  to = "https://radwan2633.pythonanywhere.com/:splat"
  status = 200
