# netlify.toml

# إعدادات البناء الأساسية
[build]
  command = "pnpm run build"
  publish = "dist"

# --- قواعد إعادة التوجيه (البروكسي) ---

# القاعدة الوحيدة التي نحتاجها هي للقرآن والقرآءات
[[redirects]]
  from = "/quran-api/*"
  to = "https://api.quranpedia.net/v1/:splat"
  status = 200
  force = true
